name: List Runner Group Contents
on:
  issues:
    types: [ opened, edited ]
jobs:
  list:
    if: ${{ contains(github.event.issue.title, 'List Organization Runner Group Contents') }}
    name: List Runner Group Contents
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: lindluni/org-runner-manager@main
        with:
          action: group-list
          authorized_team: authorized-org-runner-managers
          repo: org-runner-manager-test
          token: ${{ secrets.TOKEN }}
