name: Create Runner Group
on:
  issues:
    types: [ opened, edited ]
jobs:
  create:
    if: ${{ contains(github.event.issue.title, 'Create Organization Runner Group') }}
    name: Create Runner Group
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: lindluni/org-runner-manager@main
        with:
          action: group-create
          authorized_team: authorized-org-runner-managers
          repo: org-runner-manager-test
          token: ${{ secrets.TOKEN }}
