name: Add Repos to Runner Group
on:
  issues:
    types: [ opened, edited ]
jobs:
  add:
    if: ${{ contains(github.event.issue.title, 'Add Repos to Organization Runner Group') }}
    name: Add Repos to Runner Group
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: lindluni/org-runner-manager@main
        with:
          action: repos-add
          authorized_team: authorized-org-runner-managers
          repo: org-runner-manager-test
          token: ${{ secrets.TOKEN }}
