name: Remove Repos from Runner Group
on:
  issues:
    types: [ opened, edited ]
jobs:
  remove:
    if: ${{ contains(github.event.issue.title, 'Remove Repos from an Organization Runner Group') }}
    name: Remove Repos from Runner Group
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: lindluni/org-runner-manager@main
        with:
          action: repos-remove
          authorized_team: authorized-org-runner-managers
          repo: org-runner-manager-test
          token: ${{ secrets.TOKEN }}
